# Generated by Django 3.1.1 on 2020-09-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='display_picture',
            new_name='upload',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='technologies',
        ),
    ]
